### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by william-xue** [limintao/vue-turn-clock#1]
Module parse failed: Unexpected token (5:44)
You may need an appropriate loader to handle this file type.
| const N = (e, n) => {
|   if (e.install = (o) => {
|     for (const t of [e, ...Object.values(n ?? {})])
|       o.component(t.name, t);
|   }, n)

**Comment by limintao** [comment]
请提供一下生态环境，示例：
Vue Version: 3.3.4
Build Tool: Vite

**Comment by limintao** [comment]
> 模块解析失败：意外的标记 (5:44) 您可能需要适当的加载程序来处理此文件类型。 | 常量 N = (e, n) => { | if (e.install = (o) => { | for (const t of [e, ...Object.values(n ?? {})]) | o.component(t.name, t); | } , n)

babel版本不支持原因，推荐安装@babel/plugin-transform-nullish-coalescing-operator
然后在 babel.config.js 添加：
{ 
    "plugins": ["@babel/plugin-transform-nullish-coalescing-operator"]
}
