### ISSUE TITLE
当我切换到其它页面时，当前时间会暂停走动

### ISSUE THREAD

**Issue by zhang-sansi** [limintao/vue-turn-clock#2]
作者你好！
我在使用时遇到一个问题：
我把浏览器切换至其它标签页一段时间（至少4-5分钟）后，时间会暂停走动，再切换回去会继续从暂停的地方开始，导致显示的时间与实际时间不一致。
![image](https://github.com/limintao/vue-turn-clock/assets/110795910/0b8c35f5-0c1d-45c3-981e-10387c3078ed)

**Comment by limintao** [comment]
可以使用document.addEventListener('visibilitychange', () => {}) 监听标签页是否展示，重新设置current时间。

**Comment by limintao** [comment]
> 作者你好！ 我在使用时遇到一个问题： 我把浏览器切换至其他标签页面一段时间（至少4-5分钟）后，时间会暂停走动，再切换回去会继续从暂停的位置开始，导致显示的时间与实际时间不一致。 ![图像](https://private-user-images.githubusercontent.com/110795910/296107254-0b8c35f5-0c1d-45c3-981e-10387c3078ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzUxNTEsIm5iZiI6MTcwNTAzNDg1MSwicGF0aCI6Ii8xMTA3OTU5MTAvMjk2MTA3MjU0LTBiOGMzNWY1LTBjMWQtNDVjMy05ODFlLTEwMzg3YzMwNzhlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNDQ3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTlmMzlkN2UwOGJlNGRiOGJlOTA5ZGM3ZjdjYWM3NjlkMzc4YWE4YTgwZWVlODc4YjQyYWI1NWYyNjAwOTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mJgopFyN1ibLa-QInIbLJpivWgQR1hZ9cQOzNj7D56A)

可以使用document.addEventListener('visibilitychange', () => {}) 监听标签页是否显示，重新设置当前时间。

**Comment by zhang-sansi** [comment]
> > 作者你好！我在使用时遇到一个问题：我把浏览器切换至其他标签页面一段时间（至少4-5分钟）后，时间会暂停走动，再切换回去会继续从暂停的位置开始，导致显示的时间与实际时间不一致。![图像](https://private-user-images.githubusercontent.com/110795910/296107254-0b8c35f5-0c1d-45c3-981e-10387c3078ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzUxNTEsIm5iZiI6MTcwNTAzNDg1MSwicGF0aCI6Ii8xMTA3OTU5MTAvMjk2MTA3MjU0LTBiOGMzNWY1LTBjMWQtNDVjMy05ODFlLTEwMzg3YzMwNzhlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNDQ3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTlmMzlkN2UwOGJlNGRiOGJlOTA5ZGM3ZjdjYWM3NjlkMzc4YWE4YTgwZWVlODc4YjQyYWI1NWYyNjAwOTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mJgopFyN1ibLa-QInIbLJpivWgQR1hZ9cQOzNj7D56A)
> 
> 可以使用document.addEventListener('visibilitychange', () => {}) 监听标签页是否显示，重新设置当前时间。

可以啦，谢谢！
